spring:
  application:
    name: micrometer-prometheus

  ################################
  # 동일 Bean Name 에러 방지
  ################################

  main:
    allow-bean-definition-overriding: true

  ################################
  # Spring MVC Path Matcher
  ################################

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  ################################
  # Spring Boot Auto Configuration
  ################################

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  ################################
  # Quartz Auto Configuration
  ################################

  quartz:
    auto-startup: true
    job-store-type: memory
    jdbc:
      initialize-schema: always   # change this value

  zipkin:
    base-url: http://localhost:9411
    enabled: true

##################################
# SpringDoc OpenAPI Configuration
##################################

springdoc:
  version: '@project.version@'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/**
  api-docs:
    path: /api/api-docs

#############################
# Application Configuration
#############################

app:
  prometheus:
    job-name: spring
    grouping-key: ${spring.application.name}
    push-gateway:
      url: localhost:9091
      credentials:
        enabled: false
        username: admin
        password: XnK4tuFhMrAGcbsdkX2G7tf2q8

#############################
# Logging Configuration
#############################

logging:
  config: classpath:/logback.xml

#############################
# Management Configuration
#############################

management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#        include: prometheus, metrics, info, health, shutdown, beans

  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"