spring:
  application:
    name: micrometer-prometheus

  ################################
  # 동일 Bean Name 에러 방지
  ################################

  main:
    allow-bean-definition-overriding: true

  ################################
  # Spring MVC Path Matcher
  ################################

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  ################################
  # Spring Boot Auto Configuration
  ################################

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

##################################
# SpringDoc OpenAPI Configuration
##################################

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api/v1/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/v1/**

#############################
# Application Configuration
#############################

app:
  prometheus:
    job-name: spring
    grouping-key: ${spring.application.name}
    pushgateway-url: localhost:9091

#############################
# Logging Configuration
#############################

logging:
  config: classpath:/logback.xml

#############################
# Management Configuration
#############################

management:
  server:
    port: 9000
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans
